nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmScopes:
  privscope:
    npmRegistryServer: http://devfu-registry.flowbyte.net/

unsafeHttpWhitelist:
  - devfu-registry.flowbyte.net